name: call deploy

on: push

jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Api
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/MuscariServer/muscari-web/actions/workflows/deploy-article.yml/dispatches \
            -d '{"event_type":"update-articles"}'